### ISSUE TITLE
滥用异步导致mounted和created执行次序不正确

### ISSUE THREAD

**Issue by firstrose** [luoyunchong/lin-cms-vue#3]
vue的mounted和created被设计为有先后次序的同步调用，created应该先于mounted执行。

但是在本框架里，所有的api wrapper（例如src/plugin/base/model/base.js）被设计为async，导致mounted和created必须被说明为async，导致mounted在created结束之前就开始执行。结果是在mounted里无法正常获取通过created初始化的数据。

例子见article-form

**Comment by luoyunchong** [comment]
@firstrose 你说的问题的确存在，在生命周期create   mounted中，使用异步 方法，不能保证方法 的执行顺序。
你说的article-form中我重现了这个问题，顺序是执行不对，但是对于这个界面 来说，没有受到影响。

如果你要保证mounted中的方法得到created方法的数据。

可以把mounted中的方法，复制到created中。因为请求数据都是异步，要么你通过回调  .then得到。要么也只能异步await。
